# Use the official MySQL image as the base
FROM mysql:5.7

# Set environment variables for MySQL
ENV MYSQL_DATABASE=mydatabase \
    MYSQL_ROOT_PASSWORD=myrootpassword \
    MYSQL_USER=myuser \
    MYSQL_PASSWORD=mypassword

# Optional: Add custom configuration
COPY my-custom.cnf /etc/mysql/conf.d/

# Optional: Initialize the database
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/

EXPOSE 3306
