# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL root user password
ENV MYSQL_ROOT_PASSWORD=admin

# Expose MySQL port (3306 by default)
EXPOSE 3306
