name: Build Docker Images

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set timestamp variable
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d)"

      - name: Build App Docker image 
        run: docker build -t danikais/danikais:latest -f Dockerfile .

      - name: Build Database Docker image
        run: docker build -t danikais/mysql:latest -f Dockerfile.mysql .

      - name: Build phpMyAdmin Docker image
        run: docker build -t danikais/php:latest -f Dockerfile.php .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push App Docker image
        run: docker push danikais/danikais:latest

      - name: Push Database Docker image
        run: docker push danikais/mysql:latest

      - name: Push phpMyAdmin Docker image
        run: docker push danikais/php:latest
