name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  mysql:
    name: Build MySQL Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MySQL Docker image
        run: docker build -t danikais/liabilitymanager-mysql:latest -f dockerfile.mysql .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push MySQL Docker image
        run: docker push danikais/liabilitymanager-mysql:latest

  php:
    name: Build PHP Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PHP Docker image
        run: docker build -t danikais/liabilitymanager-php:latest -f dockerfile.php .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push PHP Docker image
        run: docker push danikais/liabilitymanager-php:latest
