name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Frontend Docker image
        run: docker build -t danikais/liabilitymanager-frontend:latest ./Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Docker image
        run: docker push danikais/liabilitymanager-frontend:latest

  backend:
    name: Build Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Backend Docker image
        run: docker build -t danikais/liabilitymanager-backend:latest ./Dockerfile.php

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker image
        run: docker push danikais/liabilitymanager-backend:latest

  mysql:
    name: Build MySQL Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MySQL Docker image
        run: docker build -t danikais/liabilitymanager-mysql:latest ./Dockerfile.mysql

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push MySQL Docker image
        run: docker push danikais/liabilitymanager-mysql:latest
