name: Build Docker Images

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build App Docker image + ":$BUILD_NUMBER"
        run: docker build -t danikais/danikaistest -f Dockerfile .

      - name: Build Database Docker image
        run: docker build -t danikais/mysqltest -f Dockerfile.mysql .

      - name: Build phpMyAdmin Docker image
        run: docker build -t danikais/phptest -f Dockerfile.php .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push App Docker image
        run: docker push danikais/danikaistest

      - name: Push Database Docker image
        run: docker push danikais/mysqltest

      - name: Push phpMyAdmin Docker image
        run: docker push danikais/phptest
